---
title: "Visualization of Functional Enrichment Result"
author: "\\

	Guangchuang Yu\\

        School of Public Health, The University of Hong Kong"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{enrichplot introduction}
  %\VignetteDepends{ggplot2}
  %\VignetteDepends{ggraph}
  %\usepackage[utf8]{inputenc}
---



```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = TRUE)

library(DOSE)
library(org.Hs.eg.db)
library(clusterProfiler)
library(ggplot2)
library(ggraph)
library(cowplot)
library(enrichplot)
```


## Induced GO DAG graph

```{r fig.width=12, fig.height=8}
library(clusterProfiler)
data(geneList)
de <- names(geneList)[abs(geneList) > 2]
ego <- enrichGO(de, OrgDb = "org.Hs.eg.db", ont="BP", readable=TRUE)

library(enrichplot)
goplot(ego)
```

## Bar plot

```{r fig.width=12, fig.height=8}
barplot(ego, showCategory=20)
```

## Dot plot

```{r fig.width=12, fig.height=8}
dotplot(ego, showCategory=30)

go <- enrichGO(de, OrgDb = "org.Hs.eg.db", ont="all")
dotplot(go, split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale="free")
```


## Gene-Concept Network

```{r fig.width=12, fig.height=8}
## remove redundent GO terms
ego2 <- simplify(ego)
cnetplot(ego2, foldChange=geneList)
cnetplot(ego2, foldChange=geneList, circular = TRUE)
```

## Enrichment Map

```{r fig.width=12, fig.height=8}
mapplot(ego2)
```

## ridgeline plot for expression distribution for GSEA result

The `ridgeplot` will visualize expression distributions of core enriched genes
for GSEA enriched categories.

```{r fig.width=12, fig.height=8, message=FALSE}
kk <- gseKEGG(geneList, nPerm=10000)
ridgeplot(kk)
```

